### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by mouamoua** [isaacsobczak/BR16GroupAssignment1#23]
Should there be a notification that pops up with a 'FileNotFoundException"?  Or when a 'ParseException' is thrown when an incorrect file type is passed into the program?  Just a thought.  However, overall everything runs great at the moment.  These are just small things we could add but aren't really necessary.

**Comment by isaacsobczak** [comment]
@mouamoua, are you able to build a runnable jar?

**Comment by isaacsobczak** [comment]
@mouamoua If you can, we can create a release, and then you can add your jar to it.

**Comment by mouamoua** [comment]
I built a runnable jar with it and it works perfectly.

**Comment by dangullings** [comment]
There's lots of things we could do to make it a better user experience. It's not the most intuitive program and I am sure a user could break it.

**Comment by isaacsobczak** [comment]
@dangullings, yep, you're right. Unless everyone is nocturnal, I'm guessing we should cut a release and add the jar.

@mouamoua, can you create a new branch from master, create a runnable jar, add the runnable jar to the project, and then create a pull request. We'll merge that, create a release, and since you checked in the jar, I'll be able to add it as a binary to the release.

**Comment by mouamoua** [comment]
@isaacsobczak also, the json file with the initial data (ie. example.json) has to be in the same directory for it to use the 'Load' function.
@dangullings true.  As of now, it works and meets the requirements.  But we could make it more user-friendly forsure.

**Comment by Robert1960** [comment]
FYI: my two cents.  The requirement was not to make a bulletproof user experience, the requirement was to load a file and add some controls around settings and data display.


If the requirements aren't in existence, it isn't going to be part of the grade.  As long as the process for executing the program in accordance with the requirements is documented, the grading requirements are met.  Remember,this is a class project to be completed in a couple weeks with two paragraphs of requirements.  Don't make it more complicated than it needs to be.

**Comment by Robert1960** [comment]
I added exception handling and error reporting to the UI
