### ISSUE TITLE
Create Basic Reading and Patient classes

### ISSUE THREAD

**Issue by isaacsobczak** [isaacsobczak/BR16GroupAssignment1#5]
I'll go about creating the fields, constructors, getters, and setters for these two basic classes.
The reading class will represent one reading from a file. Patients will have a collection of readings, and so on. In the PR, I'll also suggest we separate the file parsing functionality from the Reading entity itself, so the parsing functionality that was started will still be there in its entirety, I'll just rename the class.

**Comment by isaacsobczak** [comment]
Still working on this. I discovered that we'll need a place to objectify the collection returned from the json parser. The contents of the file plus any added readings plus a list of which patients are in the trial will belong to a Trial class.

**Comment by Robert1960** [comment]
I integrated the reader with the UI to load and display the contents of a file.

**Comment by isaacsobczak** [comment]
@Robert1960, that sounds great! I'll be using that collection that the reader spits out as a parameter in the Reading constructor. There will also be a constructor for when we add readings manually. These readings are all in a list of readings for a Trial, then we'll have a method that will take all the readings in that collection, and print them. I'm hoping that will combine well with the code you just mentioned, so long as part of what you've got there is using your swt file chooser to pick the file and pass that to the son reader.

**Comment by isaacsobczak** [comment]
#8 contains the code for this issue. Check it out! It should give us something to talk a bit about tonight. Thanks!
