### ISSUE TITLE
New simplified design idea

### ISSUE THREAD

**Issue by idgormley** [isaacsobczak/BR16GroupAssignment1#7]
I thought of a way to really simplify the program into only two classes while still meeting all the requirements
heres the link to the revised class diagram
https://go.gliffy.com/go/share/s5f2y45y8kjtd7s45m0r
let me know if this would work

**Comment by idgormley** [comment]
Also the trial value is boolean, add makes it true end makes it false and it has to be true to add reading.

**Comment by isaacsobczak** [comment]
@idgormley, I ended up having that on the Patient class in my pull request. If we have some class time, we can go over it together.
